name: Cypress Tests - Chrome

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-chrome:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar dependências
      run: npm install

    - name: Rodar Cypress no Chrome (especificando specs)
      # roda todos os specs dentro de cypress/e2e (ajuste o glob conforme desejar)
      run: npx cypress run --browser chrome --spec "cypress/e2e/**/*.js"

    - name: Upload de Artefatos (vídeos e screenshots)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-artifacts
        path: |
          cypress/screenshots
          cypress/videos
